### ISSUE TITLE
プラスアイコンが既読の操作用だということがわかりにくい

### ISSUE THREAD

**Issue by aoi1** [tokoroten/vein_support#12]
プラスアイコンをクリックすると既読？になるのだと思いますが（自信ないので違ったらすみません）、プラスアイコンだと直感的に「何かを追加する」操作に感じるのでわかりづらいです。
クリックしたあとチェックなど既読になったことがわかるアイコンに変更する、プラスアイコンにツールチップをつけて既読にする操作だということがわかる、などの案があります。

**Comment by yuukinajima** [comment]
@blux2 
おっしゃる通り、プラスアイコンをクリックするのは既読にするための操作です。
色々なご提案ありがとうございます、助かります。こちらでも考えてみます。

**Comment by tokoroten** [comment]
ひとまずチェックアイコンに変えてみましたがこれでどうでしょうか。

![image](https://user-images.githubusercontent.com/962298/54508785-64fb0e00-498a-11e9-98cf-187767940a76.png)
