### ISSUE TITLE
同じコメントが2回投稿されることがある

### ISSUE THREAD

**Issue by yosshi** [tokoroten/vein_support#14]
<img width="571" alt="2019-01-31 18 12 58" src="https://user-images.githubusercontent.com/41183/52043761-df5f0280-2583-11e9-9aa0-191501f5d670.png">

どのタイミングで投稿されるかわからないのですが、同じコメントが2回投稿されることがあります。
使用しているブラウザが brave だから悪いのか。原因はつかめないのですが。

* バージョン: 0.58.21 Chromium: 71.0.3578.98（Official Build） （64 ビット）

**Comment by tokoroten** [comment]
ダブルサブミット対策のコードが入ったのでひとまずclose
