### ISSUE TITLE
RSSフィードのリダイレクトに対応していない

### ISSUE THREAD

**Issue by kunitake** [tokoroten/vein_support#17]
RSSフィードは 

- 301 Moved Permanently

を返して、移動することがあります。現状 Vein はリダイレクトには対応していないようです。

例：http://seclists.org/rss/fulldisclosure.rss

リダイレクトに追従するようにして頂けると嬉しいです。

**Comment by tokoroten** [comment]
使っているライブラリに、リダイレクト回数の指定があるので、ちょっと増やしてみて実験してみます。
とはいえ、デフォルト値5回なので、5回以上リダイレクトしているとはちょっと考えづらいですが…。

**Comment by yuukinajima** [comment]
調査したところ、リダイレクトではなくdescriptonフィールドの取り扱いに問題があり、エラーが起きてました。
現在は正常に登録が可能です。
またエラーの表示もわかりやすくなるように修正をしました。
