### ISSUE TITLE
Subscribe new feedで登録済みの feed を入力した時の動きが分かりづらい

### ISSUE THREAD

**Issue by kunitake** [tokoroten/vein_support#18]
Subscribe new feed で登録済みの feed を入力しても、登録済みである旨の
メッセージやエラーなどが表示されないため、登録できたのか、重複している
のかの判断が付きづらい。

可能でしたら登録済みである旨のメッセージを表示して頂けると嬉しいです。

**Comment by tokoroten** [comment]
これは実装が簡単なので、対応します。

**Comment by kunitake** [comment]
ありがとうございます！他でも SUBMIT 押したあとに設定が反映されたかどうかがわからない時があるので、改善して頂けると嬉しいです（別のissueにしたほうがよければ別途登録させて頂きます）

**Comment by tokoroten** [comment]
ひとまず、こんな感じの対応をしましたがこれでイメージあってますでしょうか？

![image](https://user-images.githubusercontent.com/962298/54752747-7f4f1900-4c22-11e9-8977-c7fbbae4ed9a.png)

**Comment by kunitake** [comment]
ありがとうございます。わかりやすくなったと思います

**Comment by tokoroten** [comment]
デプロイされたのでclose
