### ISSUE TITLE
Sign up 時の Validation error がわかりにくい

### ISSUE THREAD

**Issue by ShokoTsuji** [tokoroten/vein_support#20]
Space name のエラーなのか User name のエラーなのかわかりにくい
使えない文字を使っているのか既に使っている人がいるのかのヒントが必要

**Comment by yuukinajima** [comment]
少しメッセージを改善

**Comment by ShokoTsuji** [comment]
改善メッセージ例
<img width="794" alt="Screen Shot 2019-03-25 at 12 09 45" src="https://user-images.githubusercontent.com/47136143/54897095-625c6380-4f0a-11e9-8b22-b1d9344e0270.png">
