### ISSUE TITLE
パスワードを忘れて変更しようとすると、正しいパスワードを要求される

### ISSUE THREAD

**Issue by kagurazakarasen** [tokoroten/vein_support#23]
https://open.vein.space/#/request_reset_password
でパスワードのリセットを要求し、届いたメールのリンク先からパスワードをリセットしようとすると、その前に忘れたはずのパスワード入力を即されて先にすすめなくなってしまいます。

**Comment by yuukinajima** [comment]
急いで確認して修正します。

**Comment by yuukinajima** [comment]
@kagurazakarasen
動作確認したのですが、再現しませんでした。
使ってるブラウザやメーラーの情報を教えていただけますか？

support@nextint.co.jp 
こちらでも対応可能です。

**Comment by kagurazakarasen** [comment]
すみません、こちら勘違いでした。

ブラウザはchromeバージョン: 73.0.3683.86（Official Build） （64 ビット）ですが、
新しいパスワードを２つ入力しても
「password does not match」表示が消えず、RESET PASWORDボタンが有効にならなかったのでてっきり忘れた昔のパスワードを入力しなくてはいけないと思い込んでいました。
フォーカスを入力部分から動かしたら正常にリセットできるようになりました。
お騒がせしましたですｍ（＿＿）ｍ

**Comment by tokoroten** [comment]
なるほど、これは確かにわかりづらいですね。
新しいパスワードを入れるように明示されていないため、確かに勘違いしそうです。
ちょっと文言を弄っておきますね。

![image](https://user-images.githubusercontent.com/962298/55116031-58fd1200-5129-11e9-9491-a47a53b07eae.png)
