### ISSUE TITLE
Slack以外の互換ツールにも投稿したい

### ISSUE THREAD

**Issue by peccu** [tokoroten/vein_support#30]
Slackではなく Rocket.Chat というチャットツールを使っていて、Slackのようにwebhookが利用できます。
ドメインによる制限(推測)がなければ他のwebhookが利用できるツールと連携しやすいと思います。
ご検討いただけますと幸いです。

**Comment by tokoroten** [comment]
実は同じ要望をidobataからも受けていて、裏技的にドメイン制限を外す機能を付けてあります。
よろしければ、こちらをご覧ください。
https://github.com/idobata/idobata-hooks/pull/95

**Comment by peccu** [comment]
ありがとうございます。試してみます。
面白い裏技ですね

**Comment by tokoroten** [comment]
Slack以外のWebhookはサポートが難しいため、このような暫定的な対応になっています。

**Comment by peccu** [comment]
確かにサポートは大変ですね。
提示いただいた方法で解決できたのでここはクローズします。ありがとうございました。
