### ISSUE TITLE
コメントをつけるために右端のアイテムを展開すると要素が意図せぬところにジャンプすることがある

### ISSUE THREAD

**Issue by tk0miya** [tokoroten/vein_support#32]
open.vein.space でブックマークの一覧を見ているときに、画面右端に配置されたアイテムを展開すると要素が意図せぬところにジャンプすることがあります。
そのため、コメントをつけようとしたものの対象のブックマークを見失うことがあります。

**Comment by tokoroten** [comment]
コメントフォームを開いた際に、アイテムの場所までスクロールして移動するようにしました。
現在レビュー待ちです。　おそらく明日の昼くらいまでにはデプロイされます。

**Comment by tk0miya** [comment]
修正を確認しました。対応ありがとうございます！
