### ISSUE TITLE
認証メールのURLが間違っている

### ISSUE THREAD

**Issue by kunitake** [tokoroten/vein_support#34]
> 登録されているメールアドレスが認証されていません。 

と出ていたので、認証メールを再送したのですが、メール本文にある認証用のURLが

undefined/#/betatester/settings/?email_verify_token=......

のように、undefined になって送られてきました。

**Comment by kunitake** [comment]
undefined の部分を

> https://open.vein.space

に置き換えてアクセスすることで、認証自体はうまくいきました

**Comment by tokoroten** [comment]
変数がtypoしていました。早急に対応します。

**Comment by tokoroten** [comment]
対応してデプロイしました。
