### ISSUE TITLE
左ペイン > spaces のUIは チェックボックスじゃないほうが良さそう

### ISSUE THREAD

**Issue by macinjoke** [tokoroten/vein_support#36]
左ペイン > spaces でspace を選び画面遷移するところですが、 チェックボックスだと複数選べる感がでてしまい、混乱のもとになりそうだと思いました。

**Comment by tokoroten** [comment]
とりあえずラジオボタンにしてみました。こんなのでどうでしょう？
しばらくしたら、デプロイされます。
![image](https://user-images.githubusercontent.com/962298/58397625-c88d7000-808c-11e9-8f48-58a6be97c3d8.png)

**Comment by macinjoke** [comment]
良いと思います！

それか現在のワークスペースだけ強調表示(アイコン置く、色変えるなど)して、他はそもそもアイコン表示しないとかですかね。

# 蛇足
最近大学の研究室メンバーでVein 使いはじめましたが、面白くなりそうです。ありがとうございます。
