### ISSUE TITLE
android で コメント入力→ 右 すると アプリが落ちる

### ISSUE THREAD

**Issue by t754** [tokoroten/vein_support#38]
## 再現方法

1. コメント欄をたくさん入力
1. 右

## 再現映像↓ 

![output](https://user-images.githubusercontent.com/14213356/59162104-72a5d700-8b26-11e9-9a85-61846d7b0e2a.gif)

## このときの環境

- ハード Pixel3 
- Android version 9

## 他

ちなみに左(←)では落ちない

**Comment by tokoroten** [comment]
私のP20 Liteでも再現しました。
おそらくフォーカスの移動に伴う何かだとは思うのですが。

ちょっとデバッガで追いかけてみます。

**Comment by tokoroten** [comment]
気づいたら治っていた
おそらくVuetify2.0にアップデートした影響と、OSのバージョンが上がった合わせ技かな？

**Comment by t754** [comment]
こちらでも確認しました. 直ってますね! ありがとうございます.
Close
