### ISSUE TITLE
Chrome ExtensionでScreenshotを削除しても、投稿記事にスクリーンショットがついてしまう

### ISSUE THREAD

**Issue by saitota** [tokoroten/vein_support#39]
## Expected Behavior
Chrome ExtensionでScreenshotを削除しても、投稿記事にスクリーンショットがついてしまう

## Actual Behavior
スクリーンショットがつかない

## Steps to Reproduce the Problem

  1. TAKE SCREENSHOT
  1. ☓ボタンでスクリーンショットを消す
  1. POST TO VEIN
  1. スクリーンショットがついた状態で記事POSTされている
 

## Specifications
  - Version: Vein Chrome Extension 0.1.13
  - Platform:MacOS mojave 10.14.6 / Version 0.68.140 Chromium: 77.0.3865.90 (Official Build) (64-bit)
  - Subsystem:

**Comment by tokoroten** [comment]
原因を特定しました、スクリーンショットを削除した際にバグがありました。
近いうちに修正版をリリースします。

**Comment by tokoroten** [comment]
バグ修正を行い、Ver0.1.14をストアに公開しました。
一時間以内の公開されるはずです。

**Comment by tokoroten** [comment]
0.1.14がストア公開されたのでClose
