### ISSUE TITLE
Slack招待リンクの有効期限が切れている

### ISSUE THREAD

**Issue by s4na** [tokoroten/vein_support#41]
https://open.vein.space/#/, https://open.vein.space/#/contact に貼られている、Vien ユーザーグループのSlack招待リンクの有効期限が切れています

**Comment by tokoroten** [comment]
ありがとうございます。修正します。

**Comment by s4na** [comment]
@tokoroten 

ありがとうございます👍

**Comment by tokoroten** [comment]
修正されているのでcloseします。close忘れ。
