### ISSUE TITLE
アカウント登録の利用規約同意について

### ISSUE THREAD

**Issue by HirokiMiyaoka** [tokoroten/vein_support#5]
アカウントを登録時、スペース名や名前など順調に入力し、パスワードを入力したところでエンターを押したところ、利用規約に同意していないのにそのままアカウントが作成されてしまいました。
エンターキーは無効化した方が良いと思います。

**Comment by yuukinajima** [comment]
確認しました。　近日中に修正します。

**Comment by yuukinajima** [comment]
@HirokiMiyaoka 修正完了しました。
