### ISSUE TITLE
フィードに付けた＋の操作がキャンセルできない

### ISSUE THREAD

**Issue by inductor** [tokoroten/vein_support#7]
フィードの右上部分の＋ボタンをキャンセルすることが出来ないのですが、これは仕様でしょうか？

**Comment by yuukinajima** [comment]
@inductor 
サイト名を記載してる場所をロングプレスで、その記事自体を削除する機能はありますが、自分だけが見なかったことになるような機能は用意していません。
削除機能は基本的にその場に不適切な記事を誤って投稿してしまった場合の救済措置なので多用しないでくれると嬉しいですね。
<img width="316" alt="screen shot 2019-01-29 at 15 36 30" src="https://user-images.githubusercontent.com/66552/51889144-fd89fe80-23db-11e9-8f7d-6573af5693ec.png">
