### ISSUE TITLE
Androidのアプリの名前が開発用の名前っぽい

### ISSUE THREAD

**Issue by tarakoKutibiru** [tokoroten/vein_support#9]
![screenshot_20190123-182814](https://user-images.githubusercontent.com/17213467/51596826-2bcf9000-1f3d-11e9-8917-87f3172aa01e.png)
"vein_android_client"になってる

**Comment by yuukinajima** [comment]
@tarakoKutibiru その通りで開発用の名前ですね。
次のバージョンでもっといい感じの名前にする予定です。

**Comment by tokoroten** [comment]
global news feedのリリース対応ついでに、ランチャーに表示される名前を変更しておきました。
最新版で、とりあえず「Vein」とだけしました。
なので、ひとまずclose
